version: "3.8"
services:
  ### Postgres Database ###
  postgres:
    container_name: pg_u22_cs
    image: postgres
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_service
      PGDATA: /data/postgres
    volumes:
      - pg_vol:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - apllication_net
    restart: unless-stopped

  ### Mysql ###
  mysql:
    container_name: businessdata
    image: businessdata:1.1
    volumes:
      - pg_vol:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - apllication_net

  ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - apllication_net

### API Spring Boot ###
  # /api/v1/price
  foreignCurrencyService:
    image: fc_service:1.0
    container_name: fc_service
    ports:
      - "8181:8080"
    networks:
      - apllication_net

  # /api/v1/task
  customerService:
    image: u22po_cs_service:1.0
    container_name: cs_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://pg_u22_cs:5432/customer_service
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
    ports:
      - "8282:8080"
    networks:
      - apllication_net

networks:
  apllication_net:
    driver: bridge
volumes:
  pg_vol:
